env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:unicorn/recommended'
  - 'plugin:promise/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'unicorn'
  - 'promise'
  - 'import'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  project: "tsconfig.json"
  ecmaVersion: 2018
  sourceType: module
rules: {}
