env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
#  - 'plugin:@typescript-eslint/strict'
#  - 'plugin:unicorn/recommended'
  - 'plugin:sonarjs/recommended'
  - 'plugin:promise/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
#  - 'plugin:security/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  project: "tsconfig.json"
  ecmaVersion: 2020
  sourceType: module
rules:
    "curly": error
    "prefer-template": error
    "@typescript-eslint/explicit-function-return-type": error
