env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/strict-type-checked'
  - 'plugin:@typescript-eslint/stylistic-type-checked'
  # - 'plugin:unicorn/recommended'
  - 'plugin:sonarjs/recommended-legacy'
  - 'plugin:promise/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
#  - 'plugin:security/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  project: "tsconfig.json"
  ecmaVersion: 2020
  sourceType: module
rules:
    "curly": error
    "prefer-template": error
    "@typescript-eslint/explicit-function-return-type": error
    "sonarjs/prefer-enum-initializers": off