name: CodSpeed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup pnpm
      uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
      with:
        cache: true

    - name: Install dependencies
      run: pnpm install --ignore-scripts --frozen-lockfile

    - name: Run benchmarks
      uses: CodSpeedHQ/action@c381be0bfd20e844fb45594f6aa182ffcd94545c # v4.15.0
      with:
        mode: simulation
        run: npx vitest bench --run
